#!/usr/bin/env zsh

alias -- '+x'='chmod +x'
alias -- '..'='builtin cd ../ && l'
alias -- '...'='builtin cd ../../ && l'
alias -- '....'='builtin cd ../../../ && l'
alias -- '.....'='builtin cd ../../../../ && l'
alias -- '?'='which'

alias -g g='command -p git'
alias ga='g add'
alias gau='ga --update'
alias gc='g commit --signoff'
alias gca='gc --amend --reset-author'
alias gcm='gc --message'
alias gd='g diff'
alias gds='gd --staged'
alias gnuke='g clean -fxd && g reset --hard'
alias gps='g pull'
alias gps='g push'
alias gr='g reset'
alias grs='gr --staged'
alias grv='g remote --verbose'
alias gs='g status'

alias -g l='command -p ls --color'
alias la='l -a'
alias ll='l -l'
